{{- if default .Values.rollout.enabled false }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aio.fullname" . }}-preview
  labels:
    {{- include "aio.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "aio.selectorLabels" . | nindent 4 }}
{{- end }}


