{{- if .Values.istio.virtualservice.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "aio.fullname" . }}
spec:
  hosts:
  - all-in-one.fredcorp.com
  gateways:
  - {{ .Values.istio.gateway }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: {{ .Values.service.port }}
        host: {{ include "aio.fullname" . }}-active.{{ .Values.targetNamepace }}.svc.cluster.local
{{- end }}
