---
name: Helm AIO build
on:
  push:
    branches:
      - "main"
    paths:
      - "chart/**"
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - "main"
    paths:
      - "chart/**"
  workflow_dispatch:
jobs:
  aio-helm-build:
    uses: ixxeL-actions/workflows/.github/workflows/helm-build.yaml@fix/helm-build
    with:
      workingdir: chart
      helm-values-file-test: values.yaml
    secrets:
      GHA_TOKEN: ${{ secrets.GHA_TOKEN }}
      CHARTMUSEUM_PASSWORD: ${{ secrets.CHARTMUSEUM_PASSWORD }}

